name: usefulgnom
# Conda/Mamba environment file,
# to be used when running the snakemake pipeline, 
# see workflow/README.md
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - snakemake=8.18.2
  - poetry=1.8.3
  - matplotlib=3.9.2
  - pandas=2.2.2
  - seaborn=0.13.2
  - pip
  - pip:
    - -e .